ans = '{"answer": "<p>Harry, I think I understand what you<sq>re saying and what you<sq>re trying to achieve when you say <dq>trying a bit,<dq> <dq>musical direction,<dq> and <dq>forward push,<dq> but I think the answer may be the opposite of what you may think it is. Musical direction and meaning doesn<sq>t come from individual notes, but from the relationship of one note to another, one phrase to another, and how they all fit into the story that you<sq>re telling. Think
of a movie. Not every ounce of emotion and meaning is put into each scene, and many scenes are actually without much action or meaning on their own, but when paced properly and connected effectively with the surrounding scenes, it<sq>s the whole movie that tells the story. The scenes, however, must move the story forward, not by trying express so much in each scene, but by doing its part to maintain and move the thread of the story all the way through to the end of the movie. When done well,
you forget that you<sq>re watching a movie, and you<sq>re just experiencing the story.</p><br><br><p>To translate this into your trumpet playing, your <dq>music direction<dq> (as opposed to <dq>context<dq>) reference probably shouldn<sq>t be applied to each note, but to the thought about how each note fits in to the phrase and piece as a whole. In other words, make sure that you mean each note and that you are clear on exactly how that note should sound in order for that phrase to
express what you<sq>re trying to say. From a technical perspective, it could be something as simple as the ending of phrases, when you run out of breath, pinch the note off, or intonation goes haywire. In order for the next phrase to sound as if it logically follows the previous phrase, you have to end the previous phrase with that knowledge in mind. Many beginners play <dq>vertically<dq> – one note at a time, one bar at a time, or one phrase at a time –\xa0without enough
thought about what happened in the previous phrase, or about what is about to happen in the next phrase.</p><br><br><p>To use a trumpet example, think of the first phrase of the Haydn concerto. Following the contours of the rising notes, it<sq>s obvious how that phrase should be shaped. So, as you play it, don<sq>t let anything get in the way of the logical build-up to that high point. I think of it as three mini-waves, each one ebbing and flowing, but each one cresting a little
higher than the last, and each one building on the last. One phrase doesn<sq>t have much meaning without the phrases surrounding it<colon> Daaa daaa da, da da-da-da-da <em>daaa</em>, da <strong><em>da-da-da-da</em></strong> daaa ... </p><br><br><p>In summary, what you<sq>re trying to achieve is more mental than physical. Once you have a clear idea of what you<sq>re trying to say, the mechanics of how you will say it will be clearer, and the individual notes will more naturally have
the meaning and sense of direction you<sq>re looking for. The rest is just trumpet playing, the mechanics, not music.</p><br><br><p>(After listening to the Balsom clip that you referenced, I wonder if you<sq>re referring more to the sound and how each note is so vivid and alive, and how they inevitably flow to the next note. Both Balsom and the singer do this very well. If this is what you<sq>re talking about, then it starts by having excellent technique – perfect intonation, each
note slotted dead center, and good air support. When each note is slotted like that, with a nice, relaxed core sound, it naturally gives the sense of inevitability, or <dq>moving forward,<dq> you would say it. It<sq>s dynamic and effortless. When it<sq>s out of tune, or you<sq>re not centered in the slot of each note, or too tight, the sound is static and pondering. The former is timeless, while the latter is <dq>stuck<dq> in time. It<sq>s like the difference between trying
to put a jigsaw puzzle together when you don<sq>t know how the pieces fit, vs. when you already know the picture, and layout of the pieces is logical. Hard to put into words. Of course, I could also have this all wrong.)</p><br>", "question": "<p>To create a sense of <dq>musical direction<dq>, I personally think what we need is to create a sense of music <dq>going somewhere<dq>, giving the music a <dq>forward push<dq>, if you like. </p><br><br><p>Practically
speaking, though, someone on this website (sorry, I forgot who! <colon>-() said that this means we should play every notes as if we are <dq>trying a bit<dq>. This recommendation I found to be absolutely fantastic, especially for singing in creating the sense not only of forward motion, but for colouring the note (n.b. although if we want to know <dq>where<dq> and <dq>when<dq> a note should be coloured <dq>how<dq>, we need to think harder on <dq>musical phrasing<dq>
aspect of musicality, i.e. how a note is to be connected with other notes in a phrase and meta-phrase). </p><br><br><p>But, for my main obsession, trumpet playing, I am slightly at a loss as to how best to translate this sense of <dq>trying a bit<dq> to my playing. If anyone at all therefore has any idea how, IN PRACTICAL TERMS (e.g. breathing (out) technique, embouchure formation/dynamics), I could accommodate this sense of <dq>trying a bit<dq> to my trumpet playing, then I
would be eternally grateful. </p><br><br><p>Thanks! <colon>-))</p><br>"}'
